import { createServer } from 'node:http';
import { loadConfig } from './config.js';
import { DEFAULT_DEX_REGISTRY } from './dex-registry.js';
import { RpcManager } from './rpc.js';
import { TelemetryBus } from './telemetry.js';
import { scanContract } from './scan.js';

const config = loadConfig();
const telemetry = new TelemetryBus();
const rpc = new RpcManager(config.rpcUrls, telemetry, config.maxRpcLatencyMs, config.maxBlockLag);

type Candidate = { token:string; protocol:string; pool:string; direction:string; momentum:number; risk:number; buyPressurePct:number; volumeAccelerationPct:number; uniqueBuyers:number; liquidityUsd:number; priceChangePct:number; breakoutScore:number; signal:string; status:string; reason?:string; updatedAt:number };
const state = { entriesEnabled:true, runtimeRunning:false, runtimeStop:undefined as (()=>void)|undefined, runtimeResume:undefined as (()=>void)|undefined, runtimeSellAll:undefined as (()=>unknown[])|undefined, latestBlock:undefined as bigint|undefined, rpcReady:false, rpcConnected:false, rpcChainId:undefined as number|undefined, swapsReceived:0, candidates:new Map<string,Candidate>() };
(globalThis as typeof globalThis & { __pulsehood?: typeof state }).__pulsehood = state;

const status = () => ({ app:'PulseHood', status:'ok', chainId:config.chainId, tradingMode:config.tradingMode, liveEnabled:config.liveEnabled, entriesEnabled:state.entriesEnabled, runtimeRunning:state.runtimeRunning, rpcReady:state.rpcReady, rpcConnected:state.rpcConnected, rpcChainId:state.rpcChainId??null, latestBlock:state.latestBlock?.toString()??null, rpcStatus:rpc.getStatus().map(x=>({...x,blockNumber:x.blockNumber?.toString()??null})), swapsReceived:state.swapsReceived, candidates:[...state.candidates.values()].sort((a,b)=>b.updatedAt-a.updatedAt).slice(0,100) });
const readBody = async (req: import('node:http').IncomingMessage): Promise<string> => { const chunks:Buffer[]=[]; for await(const c of req) chunks.push(Buffer.isBuffer(c)?c:Buffer.from(c)); return Buffer.concat(chunks).toString('utf8'); };
const json = (res:import('node:http').ServerResponse, code:number, body:unknown) => { if(res.headersSent||res.writableEnded)return; res.writeHead(code,{'content-type':'application/json; charset=utf-8','cache-control':'no-store'}); res.end(JSON.stringify(body)); };

const dashboardHtml = () => `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#07090d"><title>PulseHood</title><style>
:root{color-scheme:dark;font-family:-apple-system,BlinkMacSystemFont,"SF Pro Display","Segoe UI",sans-serif;background:#07090d;color:#f5f7fa}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 20% 0,#18202b 0,#07090d 45%);min-height:100vh}button,input{font:inherit}button{cursor:pointer}.shell{max-width:1180px;margin:auto;padding:16px 14px 100px}.top{display:flex;justify-content:space-between;align-items:center;gap:10px}.brand{font-size:25px;font-weight:800}.sub{font-size:12px;color:#8994a2}.pill,.badge{padding:6px 9px;border:1px solid #29323e;border-radius:9px;font-size:11px}.ok{color:#9ff0b8;border-color:#245b3a}.warn{color:#ffd68a;border-color:#5d4a20}.grid{display:grid;grid-template-columns:repeat(5,1fr);gap:8px;margin-top:16px}.card{background:#0d1117;border:1px solid #202834;border-radius:15px;padding:13px}.label{font-size:10px;color:#7f8a99;text-transform:uppercase;letter-spacing:.08em}.value{font-size:19px;font-weight:750;margin-top:5px}.tabs{display:flex;gap:6px;overflow:auto;margin:16px 0 12px}.tab,.btn{border:1px solid #29323e;background:#121820;color:#dce2e9;padding:10px 13px;border-radius:10px;min-height:42px;font-weight:700}.tab.active,.btn.primary{background:#f5f7fa;color:#07090d}.btn.danger{background:#2a1114;border-color:#5a252b;color:#ffb5bb}.panel{display:none}.panel.active{display:block}.title{font-size:16px;font-weight:750;margin-bottom:10px}.table{overflow:auto}.r{display:grid;grid-template-columns:1.5fr .65fr .55fr .8fr .8fr .65fr .9fr .8fr;gap:8px;align-items:center;padding:11px 4px;border-bottom:1px solid #1c232d;font-size:12px;min-width:800px}.head{color:#7f8a99;text-transform:uppercase;font-size:10px}.mono{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:11px}.muted{color:#8994a2}.green{color:#9ff0b8}.red{color:#ff9fa8}.yellow{color:#ffd68a}.empty{padding:25px;text-align:center;color:#7e8997}.footer{position:fixed;z-index:10;bottom:0;left:0;right:0;background:#090c11f5;border-top:1px solid #1e2631;padding:9px 12px;display:flex;justify-content:center;gap:8px}.footer .btn{min-width:150px}@media(max-width:700px){.grid{grid-template-columns:repeat(2,1fr)}.footer .btn{flex:1}.shell{padding-bottom:115px}}
</style></head><body><div class="shell"><header class="top"><div><div class="brand">PulseHood</div><div class="sub">Robinhood Chain · live scanner · paper trading</div></div><div id="health" class="pill">CONNECTING</div></header>
<section class="grid"><div class="card"><div class="label">Chain</div><div class="value">4663</div></div><div class="card"><div class="label">Latest block</div><div id="block" class="value">—</div></div><div class="card"><div class="label">RPC</div><div id="rpc" class="value">—</div></div><div class="card"><div class="label">Candidates</div><div id="count" class="value">0</div></div><div class="card"><div class="label">Bot</div><div id="bot" class="value">—</div></div></section>
<nav class="tabs"><button class="tab active" data-tab="radar">Radar</button><button class="tab" data-tab="scan">Scan</button><button class="tab" data-tab="positions">Positions</button><button class="tab" data-tab="settings">Settings</button><button class="tab" data-tab="system">System</button></nav>
<section id="radar" class="panel active"><div class="card"><div class="title">Live candidate radar</div><div class="table"><div class="r head"><span>Token</span><span>Momentum</span><span>Risk</span><span>Buy pressure</span><span>Vol accel.</span><span>Buyers</span><span>Liquidity</span><span>Signal</span></div><div id="radarBody" class="empty">Waiting for scanner data…</div></div></div></section>
<section id="scan" class="panel"><div class="card"><div class="title">Contract scan</div><div style="display:flex;gap:8px"><input id="scanInput" style="flex:1;background:#090c11;border:1px solid #2a3340;color:#fff;border-radius:10px;padding:11px" placeholder="0x token contract address"><button class="btn primary" id="scanBtn">Scan</button></div><div id="scanResult" class="empty">Scan an individual contract.</div></div></section>
<section id="positions" class="panel"><div class="card"><div class="title">Paper positions</div><div id="positionsBody" class="empty">Positions are exposed by the paper runtime telemetry.</div></div></section>
<section id="settings" class="panel"><div class="card"><div class="title">Runtime</div><div id="settingsBody"></div></div></section>
<section id="system" class="panel"><div class="card"><div class="title">RPC / telemetry</div><div id="systemBody"></div></div></section></div>
<div class="footer"><button class="btn primary" id="startBtn">START BOT</button><button class="btn danger" id="stopBtn">STOP BOT</button><button class="btn danger" id="sellBtn">SELL ALL</button></div><div id="action" style="position:fixed;bottom:66px;left:0;right:0;text-align:center;font-size:12px;color:#8994a2"></div>
<script>
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.tab).classList.add('active')});
async function get(u,o={}){const c=new AbortController(),t=setTimeout(()=>c.abort(),5000);try{const r=await fetch(u,{...o,signal:c.signal,cache:'no-store'});if(!r.ok)throw Error('HTTP '+r.status);return r.json()}finally{clearTimeout(t)}}
function fmt(n){return n==null?'—':Number(n).toLocaleString(undefined,{maximumFractionDigits:1})}function sigClass(s){return s==='BUY'?'green':s==='REJECT'?'red':'yellow'}
async function refresh(){try{const d=await get('/api/status');$('#health').textContent=d.rpcReady?'RPC READY':'RPC DEGRADED';$('#health').className='pill '+(d.rpcReady?'ok':'warn');$('#block').textContent=d.latestBlock||'—';$('#rpc').textContent=d.rpcStatus.filter(x=>x.healthy).length+'/'+d.rpcStatus.length;$('#count').textContent=d.candidates.length;$('#bot').textContent=d.runtimeRunning?'RUNNING':'STOPPED';$('#startBtn').style.display=d.runtimeRunning?'none':'inline-block';$('#stopBtn').style.display=d.runtimeRunning?'inline-block':'none';$('#radarBody').innerHTML=d.candidates.length?d.candidates.map(x=>'<div class="r"><span><b>'+esc(x.token.slice(0,10))+'…'+esc(x.token.slice(-6))+'</b><div class="muted">'+esc(x.protocol)+' · '+esc(x.pool.slice(0,10))+'…</div></span><b>'+fmt(x.momentum)+'</b><span class="'+(x.risk<=30?'green':x.risk<=50?'yellow':'red')+'">'+fmt(x.risk)+'</span><span>'+fmt(x.buyPressurePct)+'%</span><span>'+fmt(x.volumeAccelerationPct)+'%</span><span>'+fmt(x.uniqueBuyers)+'</span><span>$'+fmt(x.liquidityUsd)+'</span><span class="'+sigClass(x.signal)+'"><b>'+esc(x.signal)+'</b><div class="muted">'+esc(x.reason||x.status)+'</div></span></div>').join(''):'<div class="empty">No candidates processed yet.</div>';$('#settingsBody').innerHTML='<div class="r"><span>Mode</span><b>PAPER</b><span>Live execution</span><b class="red">DISABLED</b><span>Entries</span><b>'+ (d.entriesEnabled?'ENABLED':'STOPPED')+'</b></div>';$('#systemBody').innerHTML=d.rpcStatus.map(x=>'<div class="r"><span class="mono">'+esc(x.url)+'</span><span>'+ (x.healthy?'HEALTHY':'DEGRADED')+'</span><span>'+fmt(x.latencyMs)+' ms</span><span>block '+esc(x.blockNumber||'—')+'</span></div>').join('')}catch{$('#health').textContent='OFFLINE';$('#health').className='pill warn'}}
async function ctl(u){$('#action').textContent='Processing…';try{const d=await get(u,{method:'POST'});$('#action').textContent=d.message||'Done';await refresh()}catch{$('#action').textContent='Request failed'}}$('#startBtn').onclick=()=>ctl('/api/control/resume');$('#stopBtn').onclick=()=>ctl('/api/control/stop');$('#sellBtn').onclick=()=>ctl('/api/control/sell-all');$('#scanBtn').onclick=async()=>{const a=$('#scanInput').value.trim();$('#scanResult').textContent='Scanning…';try{const d=await get('/api/scan',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({address:a})});$('#scanResult').innerHTML=d.error?'<span class="red">'+esc(d.error)+'</span>':'<b>'+esc(d.symbol||'ERC-20')+'</b> · '+esc(d.address)+'<div class="muted">Contract: '+(d.isContract?'yes':'no')+' · decimals: '+esc(d.decimals??'—')+'</div>'}catch{$('#scanResult').textContent='Scan failed'}};refresh();setInterval(refresh,5000);
</script></body></html>`;

async function probe():Promise<void>{try{await rpc.probe();const client=rpc.getClient();const chainId=await client.getChainId();if(chainId!==config.chainId)throw Error(`RPC chain mismatch: ${chainId}`);state.rpcChainId=chainId;state.rpcConnected=true;state.rpcReady=rpc.getStatus().some(x=>x.healthy);console.log(JSON.stringify({event:'rpc_ready',chainId,rpcReady:state.rpcReady,rpcStatus:rpc.getStatus()}));}catch(e){state.rpcConnected=false;state.rpcReady=false;console.warn(JSON.stringify({event:'rpc_unavailable',message:e instanceof Error?e.message:String(e)}));}}

const server=createServer(async(req,res)=>{try{if(req.url==='/api/status'||req.url==='/health'){json(res,200,status());return}if(req.url==='/api/dex'&&req.method==='GET'){json(res,200,DEFAULT_DEX_REGISTRY.listEnabled());return}if(req.url==='/api/scan'&&req.method==='POST'){const b=JSON.parse(await readBody(req)) as {address?:string};json(res,200,await scanContract(b.address??'',rpc,telemetry));return}if(req.url==='/api/control/resume'&&req.method==='POST'){state.entriesEnabled=true;state.runtimeResume?.();json(res,200,{ok:true,entriesEnabled:true,message:'Bot entries enabled.'});return}if(req.url==='/api/control/stop'&&req.method==='POST'){state.entriesEnabled=false;state.runtimeStop?.();json(res,200,{ok:true,entriesEnabled:false,message:'New entries stopped.'});return}if(req.url==='/api/control/sell-all'&&req.method==='POST'){const closed=state.runtimeSellAll?.()??[];json(res,200,{ok:true,closedPositions:closed.length,message:`SELL ALL executed: ${closed.length} paper position(s) closed.`});return}res.writeHead(200,{'content-type':'text/html; charset=utf-8','cache-control':'no-store'});res.end(dashboardHtml());}catch(e){json(res,400,{ok:false,error:e instanceof Error?e.message:String(e)})}});
const port=Number(process.env.PORT??10000);server.listen(port,'0.0.0.0',()=>console.log(JSON.stringify({app:'PulseHood',chainId:config.chainId,tradingMode:config.tradingMode,liveEnabled:config.liveEnabled,httpPort:port})));
void probe();setInterval(()=>void probe(),15000).unref();
