import type { PublicClient, Transport } from 'viem';
import { parseAbi } from 'viem';
import { FlowEngine } from './flow.js';
import { PaperExecutionEngine } from './execution.js';
import type { ExecutionQuote, Position } from './domain.js';
import { PositionManager } from './positions.js';
import { evaluateSignal } from './signal.js';
import { RadarIngest } from './radar-ingest.js';
import { TelemetryBus } from './telemetry.js';
import { chooseBestQuote } from './quote.js';

const V2=parseAbi(['function getReserves() view returns (uint112,uint112,uint32)','function token0() view returns (address)','function token1() view returns (address)']);
const ERC20=parseAbi(['function decimals() view returns (uint8)']);
const WETH='0x0Bd7D308f8E1639FAb988df18A8011f41EAcAD73'.toLowerCase();
const USDG='0x5fc5360D0400a0Fd4f2af552ADD042D716F1d168'.toLowerCase();
const ETH_USD=Number(process.env.PAPER_ETH_USD??3000);
const ENTRY_USD=Math.max(25,Number(process.env.PAPER_ENTRY_SIZE_USD??250));
const MIN_LIQ=Math.max(1000,Number(process.env.MIN_LIQUIDITY_USD??25000));
const MIN_BUYERS=Math.max(0,Number(process.env.MIN_UNIQUE_BUYER_SCORE??20));
type Client=PublicClient<Transport>; type A=`0x${string}`; type Swap=ReturnType<RadarIngest['getRecentSwaps']>[number];
interface Market{priceUsd:number;liquidityUsd:number}
const clamp=(n:number)=>Math.max(0,Math.min(100,Number.isFinite(n)?n:0));
function id(n:number){const d=new Date();return `OPP-${d.getUTCFullYear()}${String(d.getUTCMonth()+1).padStart(2,'0')}${String(d.getUTCDate()).padStart(2,'0')}-${String(n).padStart(6,'0')}`}

export class FixedPaperTradingRuntime{
 private flow=new FlowEngine(60000); private positions=new PositionManager(); private exec:PaperExecutionEngine; private seen=new Set<string>(); private markets=new Map<string,Market>(); private timer?:NodeJS.Timeout; private seq=0; private running=false;
 constructor(private client:Client,private telemetry:TelemetryBus,private ingest:RadarIngest){this.exec=new PaperExecutionEngine(telemetry)}
 start(){if(this.running)return;this.running=true;console.log(JSON.stringify({event:'paper_strategy_started',mode:'paper',entrySizeUsd:ENTRY_USD,minLiquidityUsd:MIN_LIQ}));void this.tick();this.timer=setInterval(()=>void this.tick(),2000);this.timer.unref()}
 stop(){if(this.timer)clearInterval(this.timer);this.timer=undefined;this.running=false}
 listOpen(){return this.positions.listOpen()}
 stopEntries(){this.positions.emergencyStopEntries()}
 closeAll(){return this.positions.emergencyCloseAll()}
 private async tick(){try{const b=await this.client.getBlockNumber();const r=await this.ingest.poll(b,25n);if(!r)return;for(const s of r.swaps){const k=`${s.transactionHash}:${s.logIndex}`;if(this.seen.has(k))continue;this.seen.add(k);if(this.seen.size>5000)this.seen.delete(this.seen.values().next().value as string);await this.process(s)}await this.mark();this.telemetry.emitEvent({correlationId:TelemetryBus.correlationId('STRAT'),module:'strategy',event:'strategy_tick',block:b,status:'ok',payload:{swaps:r.swaps.length,openPositions:this.positions.listOpen().length,trackedTokens:this.markets.size}})}catch(e){console.warn(JSON.stringify({event:'paper_strategy_error',message:e instanceof Error?e.message:String(e)}))}}
 private async process(s:Swap){if(s.status!=='normalized'||!s.trader||s.direction==='UNKNOWN'||s.amountIn===undefined||s.amountOut===undefined||s.quoteToken===undefined)return;const m=await this.market(s.pool,s.targetToken,s.quoteToken);if(!m)return;this.markets.set(s.targetToken.toLowerCase(),m);const raw=s.direction==='BUY'?s.amountIn:s.amountOut,vol=this.usd(s.quoteToken,raw);if(vol<=0)return;const f=this.flow.process({swap:s,trader:s.trader,volumeUsd:vol,priceUsd:m.priceUsd,timestampMs:Date.now()});if(!f)return;const liqScore=clamp(m.liquidityUsd/MIN_LIQ*50),risk=m.liquidityUsd>=MIN_LIQ?(m.liquidityUsd>=MIN_LIQ*4?10:25):65,breakout=f.priceChangePct>=0.5?clamp(70+f.priceChangePct*10):0;const sig=evaluateSignal({flow:f,riskScore:risk,liquidityScore:liqScore,breakoutScore:breakout,liquidityUsd:m.liquidityUsd,minLiquidityUsd:MIN_LIQ,minUniqueBuyerScore:MIN_BUYERS});this.telemetry.emitEvent({correlationId:TelemetryBus.correlationId('SIGNAL'),module:'strategy',event:'signal_evaluated',token:s.targetToken,status:sig.entryQualified?'ok':'warning',payload:{signal:sig.signal,momentum:sig.momentum.score,risk:sig.risk.score,liquidityUsd:m.liquidityUsd,uniqueBuyers:f.uniqueBuyers,uniqueBuyerScore:sig.momentumInput.uniqueBuyerScore,buyPressurePct:f.buyPressurePct,volumeAccelerationPct:f.volumeAccelerationPct,priceChangePct:f.priceChangePct,breakoutScore:breakout,entryQualified:sig.entryQualified}});if(!sig.entryQualified||!this.positions.canEnter()||this.positions.listOpen().some(p=>p.token.toLowerCase()===s.targetToken.toLowerCase()))return;const amount=Math.min(ENTRY_USD,Math.max(25,m.liquidityUsd*.01)),q=this.quote(s.targetToken,m.priceUsd,m.liquidityUsd,amount),best=chooseBestQuote([q]);if(!best)return;const opportunity=id(++this.seq),cid=TelemetryBus.correlationId('ENTRY'),fill=await this.exec.buy({side:'BUY',token:s.targetToken,amountUsd:amount,quote:best.quote,correlationId:cid});if(fill.fill.executedUsd<=0)return;const now=Date.now(),p:Position={id:`${opportunity}-POS`,opportunityId:opportunity,token:s.targetToken,symbol:s.targetToken.slice(0,8),state:'DISCOVERED',entryPriceUsd:m.priceUsd,currentPriceUsd:m.priceUsd,peakPriceUsd:m.priceUsd,sizeUsd:fill.fill.executedUsd,momentumAtEntry:sig.momentum.score,momentumPeak:sig.momentum.score,openedAt:now,updatedAt:now};this.positions.add(p);this.positions.transition(p.id,'QUALIFIED');this.positions.transition(p.id,'SIGNAL');this.positions.transition(p.id,'ENTRY');this.positions.transition(p.id,'OPEN');this.telemetry.emitEvent({correlationId:cid,module:'positions',event:'paper_position_opened',token:p.token,status:'ok',payload:{positionId:p.id,opportunityId:opportunity,entryPriceUsd:p.entryPriceUsd,sizeUsd:p.sizeUsd,momentum:p.momentumAtEntry}});console.log(JSON.stringify({event:'paper_entry',positionId:p.id,opportunityId:opportunity,token:p.token,priceUsd:p.entryPriceUsd,sizeUsd:p.sizeUsd,momentum:p.momentumAtEntry}))}
 private async mark(){for(const p of this.positions.listOpen()){const m=this.markets.get(p.token.toLowerCase());if(!m)continue;const f=this.flow.process({swap:{status:'normalized',protocol:'mark',eventName:'mark',pool:p.token,transactionHash:'0x0000000000000000000000000000000000000000000000000000000000000000',logIndex:0,direction:'BUY',targetToken:p.token,quoteToken:USDG as A,amountIn:1n,amountOut:1n,trader:'0x0000000000000000000000000000000000000001',reason:undefined},trader:'0x0000000000000000000000000000000000000001',volumeUsd:1,priceUsd:m.priceUsd,timestampMs:Date.now()});if(!f)continue;const momentum=evaluateSignal({flow:f,riskScore:10,liquidityScore:100,breakoutScore:70,liquidityUsd:m.liquidityUsd,minLiquidityUsd:MIN_LIQ,minUniqueBuyerScore:MIN_BUYERS}).momentum.score,u=this.positions.updateMarket(p.id,{priceUsd:m.priceUsd,momentum,volumeAcceleration:f.volumeAccelerationPct,timestamp:Date.now()});if(u.decision.action!=='SELL')continue;const q=this.quote(p.token,m.priceUsd,m.liquidityUsd,p.sizeUsd),best=chooseBestQuote([q]);if(!best)continue;const cid=TelemetryBus.correlationId('EXIT');await this.exec.sell({side:'SELL',token:p.token,amountUsd:p.sizeUsd,quote:best.quote,correlationId:cid});this.positions.close(p.id);console.log(JSON.stringify({event:'paper_exit',positionId:p.id,priceUsd:m.priceUsd,reason:u.decision.reason}))}}
 private usd(t:A,a:bigint){const x=t.toLowerCase();return x===USDG?Number(a)/1e18:x===WETH?Number(a)/1e18*ETH_USD:0}
 private quote(token:A,price:number,liq:number,amount:number):ExecutionQuote{return{dexId:'uniswap-v2-paper',token,amountInUsd:amount,expectedAmountOutUsd:amount,executablePriceUsd:price,dexFeeUsd:amount*.003,slippageUsd:amount*.005,priceImpactUsd:amount*Math.min(.03,amount/Math.max(liq,1)),gasEstimate:120000n,gasPriceWei:1000000000n,nativeTokenUsd:ETH_USD,quotedAt:Date.now(),latencyMs:25}}
 private async market(pool:A,target:A,quote:A):Promise<Market|undefined>{try{const [t0,r,d]=await Promise.all([this.client.readContract({address:pool,abi:V2,functionName:'token0'}),this.client.readContract({address:pool,abi:V2,functionName:'getReserves'}),this.client.readContract({address:target,abi:ERC20,functionName:'decimals'})]);const [r0,r1]=r as readonly[bigint,bigint,number],is0=(t0 as string).toLowerCase()===target.toLowerCase(),qr=is0?r1:r0,tr=is0?r0:r1,qUsd=this.usd(quote,qr),units=Number(tr)/10**Number(d);if(qUsd<=0||units<=0)return;return{liquidityUsd:qUsd*2,priceUsd:qUsd/units}}catch{return}}
}
